#!/usr/bin/python3
import sys


def factorize(n):
    factors = []
    d = 2
    while d * d <= n:
        if n % d == 0:
            factors.append(d)
            n //= d
        else:
            d += 1
    if n > 1:
        factors.append(n)
    return factors

def main(filename):
    try:
        with open(filename, "r") as file:
            for line in file:
                n = int(line.strip())
                factors = factorize(n)
                factors_str = "*".join(map(str, factors))
                print(f"{n}={factors_str}")
    except Exception as e:
        print(f"Error: {e}")

if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Usage: factors <file>")
        sys.exit(1)

    filename = sys.argv[1]
    main(filename)
