#!/usr/bin/python3
import math
import sys


def get_p_q(num: int):
    limit = round(math.sqrt(num))
    for p in range(2, limit + 1):
            if num % p == 0:
                q = num // p
                print(f"{num}={q}*{p}")
                return


#check if file exists
file = None
try:
    with open(sys.argv[1], "r") as file:
        for line in file:
            num = int(line.strip())
            get_p_q(num)
except FileNotFoundError:
    print("File doesn't exist")
except IndexError:
    print("Usage: python script.py filename")
